"""init auth tables

Revision ID: 8f3de2033a2d
Revises: 
Create Date: 2026-05-01 11:42:53.114534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3de2033a2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'READER', 'AUTHOR', 'TRANSLATOR', 'MODERATOR', name='role_enum'), server_default='READER', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_entities'))
    )
    op.create_index(op.f('ix_auth_entities_email'), 'auth_entities', ['email'], unique=True)
    op.create_index(op.f('ix_auth_entities_login'), 'auth_entities', ['login'], unique=True)
    op.create_table('role_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('requested_role', sa.Enum('READER', 'AUTHOR', 'TRANSLATOR', 'MODERATOR', name='desired_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='role_request_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_requests'))
    )
    op.create_index(op.f('ix_role_requests_entity_id'), 'role_requests', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_requests_entity_id'), table_name='role_requests')
    op.drop_table('role_requests')
    op.drop_index(op.f('ix_auth_entities_login'), table_name='auth_entities')
    op.drop_index(op.f('ix_auth_entities_email'), table_name='auth_entities')
    op.drop_table('auth_entities')
    # ### end Alembic commands ###
