"""init_table_profile_&_ignore_list

Revision ID: c10c9d19ef15
Revises: 
Create Date: 2026-05-10 20:54:18.603406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10c9d19ef15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('background_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('UNSPECIFIED', 'MALE', 'FEMALE', name='profile_gender_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_index(op.f('ix_profiles_name'), 'profiles', ['name'], unique=True)
    op.create_table('ignore_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ignored_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ignored_user_id'], ['profiles.user_id'], name=op.f('fk_ignore_lists_ignored_user_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.user_id'], name=op.f('fk_ignore_lists_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ignore_lists')),
    sa.UniqueConstraint('user_id', 'ignored_user_id', name='uq_user_ignored')
    )
    op.create_index(op.f('ix_ignore_lists_ignored_user_id'), 'ignore_lists', ['ignored_user_id'], unique=False)
    op.create_index(op.f('ix_ignore_lists_user_id'), 'ignore_lists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ignore_lists_user_id'), table_name='ignore_lists')
    op.drop_index(op.f('ix_ignore_lists_ignored_user_id'), table_name='ignore_lists')
    op.drop_table('ignore_lists')
    op.drop_index(op.f('ix_profiles_name'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
